### ISSUE TITLE
Use some light-weight styling on tutorial pages

### ISSUE THREAD

**Issue by MrOtherGuy** [techboyg5/css-tutorial#3]
Right now the way tutorial pages are styled, or rather not-styled, makes them appear pretty weird considering that the tutorial is all about css.

So unless you have some other plan in mind for why they are unstyled, I think we should apply some light-weight styling to them. I'm thinking something like a grey with slight blue tint as the page background and then make the actual text paragraphs have some background-color with transparency. Also, to improve readability we should constrain the maximum width of paragraphs to something like 60-80 characters and make them if not fully centered, then at least somewhat centered. 

Shared page-navigation elements should also use their own styling that make them more noticeable.

**Comment by techboyg5** [comment]
We already have lightweight styling. In each of the pages in the tutorial, we will demonstrate what will be learned.

**Comment by MrOtherGuy** [comment]
So, is your plan to gradually add styling to various elements of the page as the reader progresses the tutorial?

**Comment by techboyg5** [comment]
> 
> 
> So, is your plan to gradually add styling to various elements of the page as the reader progresses the tutorial?

No, but when the user learns about something, there will be a demo of that feature on that page.

**Comment by techboyg5** [comment]
I'm closing this issue because I already have some styling.
